worlds:
  overworld: "nebrix_islands_overworld"
  nether: "nebrix_islands_nether"
  end: "nebrix_islands_end"

islands:
  spacing: 300
  base-y: 96
  radius-default: 100
  radius-max: 300
  home-offset: { x: 0.5, y: 0, z: 0.5 }
  endPortalPick: true   # sneak + left-click with pickaxe to move frame

limits:
  by-block:
    HOPPER: 128
    TURTLE_EGG: 0

value:
  by-block:
    DIAMOND_BLOCK: 100
    EMERALD_BLOCK: 120
    ANCIENT_DEBRIS: 250

generator:
  cobble:
    table: { COBBLESTONE: 70, COAL_ORE: 6, IRON_ORE: 5, COPPER_ORE: 5, GOLD_ORE: 3, REDSTONE_ORE: 3, LAPIS_ORE: 3, DIAMOND_ORE: 2, EMERALD_ORE: 1 }
  basalt:
    table: { BASALT: 85, BLACKSTONE: 10, MAGMA_BLOCK: 5 }
  # optional per-tier multipliers
  tiers:
    1: { weight-mult: { DIAMOND_ORE: 1.0, EMERALD_ORE: 1.0 } }
    2: { weight-mult: { DIAMOND_ORE: 1.2, EMERALD_ORE: 1.2 } }
    3: { weight-mult: { DIAMOND_ORE: 1.4, EMERALD_ORE: 1.4 } }

upgrades:
  radius: { 1: 100, 2: 150, 3: 200, 4: 250, 5: 300 }
  members: { 1: 3, 2: 5, 3: 8 }
  generator-tier-cost: { crystals: 25, coins: 15000 }

boosters:
  # minutes + multipliers
  value: { duration: 30, mult: 1.25 }
  drops: { duration: 30, mult: 1.20 }

missions:
  # simple numeric knobs; details hard-coded in code
  xp-per-complete: 25
  level-unlock:
    nether: 5
    end: 12

economy:
  provider: "vault"
  crystals-command: "nebrx givecrystals %player% %amount%"

ui:
  title-main: "<gradient:#FF5EDF:#00C9FF><bold>NEBRIX SKYBLOCK</bold></gradient>"
  header: "<gray>✦ </gray><gradient:#FF5EDF:#00C9FF><bold>NEBRIX</bold></gradient><gray> ✦</gray>"
  line: "<gray>%msg%</gray>"
  bossbar: "<gradient:#FF5EDF:#00C9FF><bold>NEBRIX</bold></gradient> <gray>•</gray> <white>%context%</white>"
  actionbar: "<gray>⏳ <white>%seconds%s</white> left</gray>"
