name: NebrixSkyblock
version: '${version}'
main: com.chunksmith.nebrixSkyblock.NebrixSkyblock
api-version: '1.21'
load: POSTWORLD
authors: [ Chunksmith ]
description: Official NebrixMC Skyblock engine — powering islands, economy, and the living sky.
website: https://chunksmith.com
commands:
  island:
    aliases: [is, skyblock]
    description: Island commands
    permission: nebrix.island
    usage: /<command>
permissions:
  nebrix.island:
    default: true
  nebrix.admin:
    default: op
