name: NebrixSkyblock
version: '0.0.1'
main: com.chunksmith.nebrixSkyblock.NebrixSkyblock
api-version: '1.21'
load: POSTWORLD
authors: [ Chunksmith ]
description: Official NebrixMC Skyblock engine — powering islands, economy, and the living sky.
website: https://chunksmith.com
commands:
  island:
    aliases: [is, skyblock]
    description: Opens the Skyblock GUI
    usage: /<command>
permissions:
  nebrix.admin:
    default: op
